### ISSUE TITLE
Probable small annotation errors

### ISSUE THREAD

**Issue by tstanislawek** [cndplab-founder/ICDAR2019_cTDaR#1]
Hi,

first of all, thank you for sharing this great dataset with annotations. 

I notice that in some files for TRACKA that are some inconsistencies:
1. in file `cTDaR_t10076.jpg` - table description `Payments on loss of office` is not part of the table 
1. In file `cTDaR_t10421.jpg` - table description `Net insurance premium income` is not part of the table

In general sometimes is hard to decide where beginning of a table (especially in context of table descriptions like on the image `cTDaR_t10041.jpg`). I also notice that in that dataset, graphical features rather then semantic structures (e.g. if we include table descriptions or not) play more role during annotation process.

**Comment by cndplab-founder** [comment]
> Hi,
> 
> first of all, thank you for sharing this great dataset with annotations.
> 
> I notice that in some files for TRACKA that are some inconsistencies:
> 
> 1. in file `cTDaR_t10076.jpg` - table description `Payments on loss of office` is not part of the table
> 2. In file `cTDaR_t10421.jpg` - table description `Net insurance premium income` is not part of the table
> 
> In general sometimes is hard to decide where beginning of a table (especially in context of table descriptions like on the image `cTDaR_t10041.jpg`). I also notice that in that dataset, graphical features rather then semantic structures (e.g. if we include table descriptions or not) play more role during annotation process.

Hi,
Thank you for your kind question and careful comment. TRACKA uses a global evaluation.
In keeping with the historical dataset(cTDaR_t0xxxx.jpg/.xml), the basic principle of modern dataset(cTDaR_t1xxxx.jpg/.xml) table region annotation is that:
1. The table descriptions(such as the titles, the notes, etc.) are not included in the table, and the BBox containing the table and its related table lines is used as a standard; 
2. At the same time, the annotations of table region are also used to facilitate the subsequent table structure recognition. 
However, some tables are more difficult to distinguish whether the text at the beginning of the table is the title or the content, so the above situation will occur. However, the final evaluation under IoU 0.6~0.9, then as long as the general range is correct, it has little effect on the final result.
What do you think ?

Feel free to check and feedback, Thanks.
